---
- name: Copy pacman configuration file
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf

- name: Refresh pacman mirrors
  pacman:
    update_cache: yes

- include: sudoers.yml
- include: packages.yml
