---
- name: Install universal base packages
  pacman:
      name: "{{ base_packages }}"
      state: present

- name: Create AUR directory
  file: path=/home/{{ user.name }}/{{ aur.dir }}
        state=directory
        owner={{ user.name }}
  tags:
    - aur
    - packages


