---

- name: Ensure required packages are installed
  become: yes
  pacman:
    name: 
      - ranger
    state: present
    update_cache: yes

- name: Copy config files
  copy:
    dest: "~/.config/"
    mode: 0755
    src: ranger
