---

- name: Ensure required packages are installed
  become: yes
  pacman:
    name: 
      - picom 
    state: present
    update_cache: yes

- name: Copy config files for picom 
  copy:
    dest: "~/.config/"
    mode: 0755
    src: picom
