---

- name: Ensure required packages are removed
  become: yes
  pacman:
    extra_args: --recursive
    name: 
      - picom
    state: absent

- name: Ensure config directory is removed
  file:
    path: 
      - "~/.config/picom"
    state: absent

